version: '3.1'
services:
  stats-server:
    build: ./stats/stats-server
    image: stats-server-image
    container_name: stats-server-container
    ports:
      - "9090:9090"
    depends_on:
      - stats-db
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://stats-db:5432/ewm-stats

  stats-db:
    image: postgres:14-alpine
    container_name: postgres-stats-db-container
    ports:
      - "6541:5432"
    environment:
      - POSTGRES_DB=ewm-stats
      - POSTGRES_USER=stats
      - POSTGRES_PASSWORD=stats
  ewm-service:
    image: amazoncorretto:11
    ports:
        - "8080:8080"
  ewm-db:
     image: postgres:14-alpine