DROP TABLE IF EXISTS hits CASCADE;

CREATE TABLE IF NOT EXISTS hits (
    id INT BIGINT GENERATED ALWAYS AS IDENTITY NOT NULL PRIMARY KEY,
    app_name VARCHAR(255) NOT NULL,
    uri VARCHAR(2000) NOT NULL,
    user_ip VARCHAR(15) NOT NULL,
    hitTimestamp  TIMESTAMP WITHOUT TIME ZONE NOT NULL
);